version: '3'

services:
  postgres:
    container_name: postgres
    build: .
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=notes
    ports:
      - 5432:5432

  server:
    container_name: server
    build: ./server/
    depends_on:
      - postgres  
    ports:
      - 3000:3000